title: Engineered By Ananya
description: Get to know Ananya
theme: just-the-docs

logo: "/assets/images/minimal_logo.svg"
# favicon_ico: "/assets/images/opendevsecops-favicon.ico"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  important:
    title: Important
    color: green  
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: blue
  definition:
    title: Definition
    color: purple
